### PR TITLE
fix: sanitize data to match edge delivery markup

### LINKED ISSUE #194: incorrect structure generated for some products
## Issue Description

A product, `adb266`, is not rendering with correct structure markup from the renderer, while another product is, `adb407`.

I deleted `adb266` content via helix api, then re-ran the poller to attempt to re-generate. I also tried deleting it and manually previewing/publishing the product from the helix api.

Also, it appears the generated azure html is wrong for `adb266` - the structure is different.

Image

### includes blocks/classnames in final helix markup 👍🏼 
- **Product**: adb407 (ecycled-performance-hat2)
- **Site URL**: https://products-ssg--plp-prerender-dev--adobe-commerce.aem.live/products/ecycled-performance-hat2/adb407
- **Plain HTML**: https://products-ssg--plp-prerender-dev--adobe-commerce.aem.live/products/ecycled-performance-hat2/adb407.plain.html
- **Overlay Source**: https://firefly.azureedge.net/a2496cffffd20d3361b8d3698449049f-public/public/pdps/products/ecycled-performance-hat2/adb407.html
- **HLX Status**: https://admin.hlx.page/status/adobe-commerce/plp-prerender-dev/main/products/ecycled-performance-hat2/adb407

### does not include blocks/classnames in final helix markup 👎🏼 
- **Product**: adb266 (adobe-premiere-pro-tee)
- **Site URL**: https://products-ssg--plp-prerender-dev--adobe-commerce.aem.live/products/adobe-premiere-pro-tee/adb266
- **Plain HTML**: https://products-ssg--plp-prerender-dev--adobe-commerce.aem.live/products/adobe-premiere-pro-tee/adb266.plain.html
- **Overlay Source**: https://firefly.azureedge.net/a2496cffffd20d3361b8d3698449049f-public/public/pdps/products/adobe-premiere-pro-tee/adb266.html
- **HLX Status**: https://admin.hlx.page/status/adobe-commerce/plp-prerender-dev/main/products/adobe-premiere-pro-tee/adb266

### Working:

* https://products-ssg--plp-prerender-dev--adobe-commerce.aem.live/products/ssg-configurable-product/ssgconfig123
* https://products-ssg--plp-prerender-dev--adobe-commerce.aem.live/products/adobe-pattern-hoodie/adb127
* https://products-ssg--plp-prerender-dev--adobe-commerce.aem.live/products/adobe-for-all-pin/adb343

### Not Working: 

* https://products-ssg--plp-prerender-dev--adobe-commerce.aem.live/products/tray-art-by-emma-zhang/adb412

### PR DESCRIPTION
**Pull request by buuhuu**
Fixes #194

### CODE REVIEW

File: actions/pdp-renderer/render.js [hunk 1]
```diff
@@ -55,12 +62,17 @@ async function generateProductHtml(sku, urlKey, context) {
       const baseUrl = getProductUrl(baseProduct, context);
       if (Array.isArray(option.values)) {
         option.values = option.values.map((value) => ({
-          ...value,
```
Comment (sirugh) [inline actions/pdp-renderer/render.js]: Was this intentional removal of the spread? Figured you would just append `title` prop after if that's all you need.

**Review by sirugh — APPROVED** [review]
I will not be able to validate/test but code looks fine. One comment regarding a change away from spreading of value props, otherwise LGTM.

**Review by baranovskyalexandr — APPROVED** [review]
